server:
  port: 8080

spring:
  application:
    name: localGeoApp

aws:
  dynamodb:
    region: us-east-2 # Change to your AWS region

# AI API Configuration
ai:
  api:
    type: gemini  # Set to 'gemini' for Google Gemini or 'openai' for OpenAI
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    model: gemini-2.5-flash
